AppCenter: Bug-Fix: Make sure that the update of the default app is made instantly.
Meeds-io/app-center pull request #140
Opened 2020-07-16 15:52 UTC by mdiha

2020-07-17 17:12 UTC, ahamdi requested changes
Please add description to the PR, I didn't get what the fix is doing exactly ?

2020-07-20 15:28 UTC, ahamdi requested changes
Won't it be better if you emit an event to update the application that had a changed avatar, WDYT ?

2020-07-20 15:36 UTC, mdiha commented
> Won't it be better if you emit an event to update the application that had a changed avatar, WDYT ?

It is not doable to update only a target app, the easy way is to re-render all the applications list.

2020-07-21 11:23 UTC, ahamdi submitted a review, later dismissed
LGTM

2020-07-21 11:52 UTC, ahamdi approved these changes

2020-07-21 11:56 UTC, merged