MAINT-26842: UI glitch in permission field
Meeds-io/app-center pull request #141
Opened 2020-07-20 09:55 UTC by AzmiTouil

hide the suggester list of permissions field when scrolling in the app center drawer

2020-07-20 14:39 UTC, ahamdi requested changes

2020-07-20 14:39 UTC, ahamdi commented on app-center-webapps/src/main/webapp/vue-apps/adminSetup/components/drawer/ExoAppCenterDrawer.vue
> +    $('.formContent').on( 'scroll', function(){
Couldn't you manage this by CSS ?

2020-07-20 15:56 UTC, AzmiTouil commented on app-center-webapps/src/main/webapp/vue-apps/adminSetup/components/drawer/ExoAppCenterDrawer.vue
> +    $('.formContent').on( 'scroll', function(){
No, I could not

2020-07-21 17:52 UTC, ahamdi commented on app-center-webapps/src/main/webapp/vue-apps/adminSetup/components/drawer/ExoAppCenterDrawer.vue
> +    $('.formContent').on( 'scroll', function(){
Ok thanks

2020-07-21 17:52 UTC, ahamdi approved these changes
LGTM

2020-07-21 18:51 UTC, merged