QWIN-37648 : Update apps icons in the app center
Meeds-io/app-center pull request #179
Opened 2020-12-09 16:47 UTC by Rdidmohamedelhadi

2020-12-15 10:26 UTC, ahamdi requested changes

2020-12-15 10:26 UTC, ahamdi commented on app-center-services/src/main/java/org/exoplatform/appcenter/service/ApplicationCenterService.java
> +          if (storedApplication.isChangedManually() && !OVERRIDE_MODE.equals(applicationPlugin.getOverrideMode())){
This check means we won't do an update at all since override is false.

2020-12-15 10:26 UTC, ahamdi commented on app-center-services/src/test/java/org/exoplatform/appcenter/service/ApplicationCenterServiceTest.java
> +      assertEquals(application.getImageFileId().longValue(),6);
Why the test is changed ? we expected null and it is not the case clearly

2020-12-16 21:08 UTC, ahamdi requested changes
Please add a Unit test to cover the new behaviour

2020-12-17 16:12 UTC, Rdidmohamedelhadi commented
> Please add a Unit test to cover the new behaviour

done!!

2020-12-17 18:40 UTC, ahamdi approved these changes
LGTM

2020-12-18 07:59 UTC, merged