Add applications center node to the navigation of Platform settings - EXO-66546 - Meeds-io/MIPs#88
Meeds-io/app-center pull request #280
Opened 2023-10-11 07:04 UTC by IlhemEssaadi

2023-10-11 23:17 UTC, azayati requested changes

2023-10-11 23:17 UTC, azayati commented on app-center-webapps/src/main/webapp/WEB-INF/conf/app-center/portal/portal/administration/pages.xml
> +    <page>
format code

2023-10-11 23:17 UTC, azayati commented on app-center-webapps/src/main/webapp/WEB-INF/conf/app-center/portal/portal/administration/pages.xml
> +  This file is part of the Meeds project (https://meeds.io/).
update header

2023-10-11 23:17 UTC, azayati commented on app-center-webapps/src/main/resources/locale/navigation/portal/administration_en.properties
> +# This file is part of the Meeds project (https://meeds.io/).
- update header
- you should declare the file into https://github.com/Meeds-io/app-center/blob/feature/experience/translations.properties#L22 like done for global site, in order to be considered by crowdin

2023-10-11 23:17 UTC, azayati commented on app-center-webapps/src/main/webapp/WEB-INF/conf/app-center/portal/portal-configuration.xml
> +        </value-param>
```suggestion
```

2023-10-11 23:17 UTC, azayati commented on app-center-webapps/src/main/webapp/WEB-INF/conf/app-center/portal/portal-configuration.xml
> +              <string>${exo.app-center.portalConfig.administration.importmode:insert}</string>
```suggestion
              <string>${exo.app-center.portalConfig.administration.importmode:merge}</string>
```

2023-10-12 11:41 UTC, azayati requested changes

2023-10-12 11:41 UTC, azayati commented on app-center-webapps/src/main/webapp/WEB-INF/conf/app-center/portal/portal/administration/pages.xml
> +    <container template="system:/groovy/portal/webui/container/UIContainer.gtmpl" cssClass="singlePageApplication">
```suggestion
    <container id="singlePageApplicationContainer" template="system:/groovy/portal/webui/container/UIContainer.gtmpl" cssClass="singlePageApplication">
```

2023-10-12 11:42 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-10-12 11:53 UTC, azayati approved these changes
LGTM

2023-10-12 11:53 UTC, merged